### ISSUE TITLE
design + skrivefeil

### ISSUE THREAD

**Issue by eirikhoem** [digdir/release.digdir.no#60]
1 . Kunne vi ha fått til Digdir-design? - Går det an med tilsvarende som på https://status.digdir.no/

2. Rette Idporten til "ID-porten"
![Skjermbilde 2024-02-06 102555](https://github.com/digdir/release.digdir.no/assets/6310801/e39b11d9-df1c-4678-9aad-f63dee88f652)

**Comment by andreasbalevik** [comment]
Implementert tilsvarende design som forespurt
